name: portal-backend-pen

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/cors-allow-origin: http://localhost:3000, https://*.dev.demo.ftcpro.co
  tls: 
    - secretName: tls-secret
      hosts:
        - portal-backend-pen.dev.demo.ftcpro.co
  hosts:
    - host: portal-backend-pen.dev.demo.ftcpro.co
      paths:
        - path: /api/registration
          pathType: Prefix
          backend:
            service: registration-service
            port: 8080
        - path: /api/administration
          pathType: Prefix
          backend:
            service: administration-service
            port: 8080
        - path: /api/notification
          pathType: Prefix
          backend:
            service: notification-service
            port: 8080
        - path: /api/provisioning
          pathType: Prefix
          backend:
            service: provisioning-service
            port: 8080
        - path: /api/apps
          pathType: Prefix
          backend:
            service: marketplace-app-service
            port: 8080

postgresql:
  secret:
    password: "<path:portal/data/pen/postgres#postgres-password>"
    replicationPassword: "<path:portal/data/pen/postgres#replication-password>"
    initUserDbSql: "<path:portal/data/pen/postgres-db-user#01-init-user-db.sql>"
  primary:
    extraVolumeMounts:
      - name: initdb
        mountPath: "/docker-entrypoint-initdb.d"
      - name: initdb-secrets
        mountPath: "/secrets"
    extraVolumes:
      - name: initdb
        emptyDir: {}
      - name: initdb-secrets
        secret:
          secretName: secret-postgres-init-db-user
    initContainers:
      - name: initdb
        image: ghcr.io/catenax-ng/product-portal-cd_initdb:latest
        imagePullPolicy: Always
        command:
          - sh
        args:
          - -c
          - |
            echo "Copying initdb secret sqls..."
            cp /secrets/* /docker-entrypoint-initdb.d
            echo "Copying initdb sqls..."
            cp -R /import/* /docker-entrypoint-initdb.d
        volumeMounts:
        - name: initdb
          mountPath: "/docker-entrypoint-initdb.d"
        - name: initdb-secrets
          mountPath: "/secrets"

registration:
  image:
    registrationtag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/pen/registration#appsettings.json>"

administration:
  image:
    administrationtag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/pen/administration#appsettings.json>"

provisioning:
  image:
    provisioningtag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/pen/provisioning#appsettings.json>"

appmarketplace:
  image:
    appmarketplacetag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/pen/appmarketplace#appsettings.json>"

portalmigrations:
  image:
    portalmigrationstag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/pen/portal-migrations#appsettings.json>"

portalmaintenance:
  image:
    portalmaintenancetag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/pen/portal-maintenance#appsettings.json>"

notification:
  image:
    notificationtag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/pen/notification#appsettings.json>"

pgadmin4:
  enabled: true
  secret:
    password: "<path:portal/data/pen/pgadmin4#password>"
  env:
    email: portal@ftcpro.co
  existingSecret: secret-pgadmin4
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: portal-pgadmin4-pen.dev.demo.ftcpro.co
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - portal-pgadmin4-pen.dev.demo.ftcpro.co
        secretName: tls-secret