apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal-backend
spec:
  destination:
    namespace: product-portal
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/portal-backend
    repoURL: 'https://github.com/niteshsakhiya/product-portal-cd.git'
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm-args
      env:
        - name: AVP_SECRET
          value: vault-secret
        - name: helm_args
          value: '-f values.yaml -f values-beta.yaml'
  project: project-portal
