apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namesapce: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/niteshsakhiya/product-portal-cd.git'
    path: charts/portal-frontend
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: product-portal
