name: "portal"
portContainer: 8080
portService: 8080
replicaCount: 1
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true

ingress:
  enabled: true

portal:
  name: "portal"
  image:
    name: "ftcpro.azurecr.io/frontend/product-portal-frontend"
    portaltag: "latest"

assets:
  name: "assets"
  image:
    name: "ghcr.io/catenax-ng/product-portal-common-assets"
    assetstag: 0.5.1

registration:
  name: "registration"
  image: 
    name: "ftcpro.azurecr.io/frontend/product-portal-frontend-registration"
    registrationtag: "latest"

demonstrator:
  enabled: false
