name: Portal InitDB

on: 
  push:
    # paths:
    #   # this workflow file
    #   - '.github/workflows/portal-initdb.yml'
    #   # Docker files
    #   - 'docker/Dockerfile.import'
    #   # sqls
    #   - 'import/**'

    # branches:
    #  - main

    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: 90 portal-initdb image built
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}_initdb

    steps:
      - name: Get tag name
        id: git-tag
        run: echo ::set-output name=git-version::${GITHUB_REF/refs\/tags\//}

      # Get the latest sources
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Portal initdb image
      - name: 'Build image'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.import
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.git-tag.outputs.git-version }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
